### ISSUE TITLE
+ (NSArray *)arrayOfColorsWithColorScheme:(ColorScheme)colorScheme for:(UIColor *)color flatScheme:(BOOL)isFlatScheme;

### ISSUE THREAD

**Issue by Mackarous** [VAlexander/Chameleon#12]
It seems to me that the compiler is looking for the method:

```Objective-C
+ (NSArray *)arrayOfColorsWithColorScheme:(ColorScheme)colorScheme for:(UIColor *)color flatScheme:(BOOL)isFlatScheme;
```

but the method, found in **NSArray+Chameleon.h/m** is the following:

```Objective-C
+ (NSArray *)arrayOfColorsWithColorScheme:(ColorScheme)colorScheme with:(UIColor *)color flatScheme:(BOOL)isFlatScheme;
```

(*with* should be *for*)

**Comment by Mackarous** [comment]
Whoops! I just realized this was apparently fixed 3 days ago! But when I pulled master today, I still had the same issue.

(https://github.com/VAlexander/Chameleon/commit/21230b0357f456d1c9a29deb4cd4aa11c2eb3999)

**Comment by VAlexander** [comment]
Hi @Mackarous! Thanks for looking into this. Just to make sure I understand correctly, you're using the latest version of Chameleon in your swift project, but it won't compile because it is still using the old ```+ (NSArray *)arrayOfColorsWithColorScheme:(ColorScheme)colorScheme for:(UIColor *)color flatScheme:(BOOL)isFlatScheme;``` method? 

I'm updating the example project now to properly call the updated method. Are you using cocoa pods?

**Comment by VAlexander** [comment]
Just updated the example project to reflect the recent changes. I also went back in and rather than completely obliterate the old method, I simply deprecated it, in favor of:

``` objective-c
+ (NSArray *)arrayOfColorsWithColorScheme:(ColorScheme)colorScheme with:(UIColor *)color flatScheme:(BOOL)isFlatScheme;
```

Just updated cocoapods as well to 1.1.2. Everything should be working now. If you have any problems, feel free to open up a new issue.

**Comment by Mackarous** [comment]
Hey I totally didn't get any notifications over this. Just wanted to say thanks a lot! Looks great. I am not using cocoa pods right now as my project is in swift.
